### ISSUE TITLE
want some knowledge

### ISSUE THREAD

**Issue by amul67142** [Aman28801/DjangoAPI#1]
sir, is this written in python language.

**Comment by Aman28801** [comment]
you can check on your own you dumb ass person.

**Comment by amul67142** [comment]
T-T 
 for me its very hard code to understand 
 i m lvl 1
pls explain so that i can start my road to development

**Comment by Aman28801** [comment]
tf you are assigning this issue to me 
lol

**Comment by Aman28801** [comment]
i am a rude person go to hell i am not gonna help you

**Comment by amul67142** [comment]
Sir pls at any cost i will provide u a russian

**Comment by Aman28801** [comment]
i dont need russian
